HCF.Web/Controllers/GoalController.cs
using HCF.BDO;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using HCF.BAL;
using HCF.Utility;
using HCF.Web.Base;
using HCF.Web.Filters;
using HCF.BAL.Interfaces.Services;
using HCF.Web.ViewModels.Goal;
using HCF.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using System.IO;
using HCF.Utility.Extensions;

namespace HCF.Web.Controllers
{
    [Authorize]
    public class GoalController : BaseController
    {

        private readonly IInsActivityService _inspectionActivityService;
        private readonly IStandardService _standardService;
        private readonly IEpService _epService;
        private readonly IGoalMasterService _goalMasterService;
        private readonly IFrequencyService _frequencyService;
        private readonly IFloorAssetService _floorAssetService;
        private readonly IAssetsService _assetService;
        private readonly IDocumentTypeService _documentTypeService;
        private readonly IIlsmService _ilsmService;
        private readonly IMainGoalService _mainGoalService;
        private readonly IOrganizationService _orgService;
        private readonly ICommonService _commonService;
        private readonly IDocumentsService _documentService;
        private readonly ITransactionService _transactionService;
        private readonly IStepsService _stepService;
        private readonly IUserService _userService;
        private readonly IHttpPostFactory _httpService;
        private readonly ICommonModelFactory _commonModelFactory;
        private readonly IPdfService _pdfService;
        private readonly IBuildingsService _buildingsService;
        private readonly IReportsService _reportService;
        public GoalController(
            ICommonModelFactory commonModelFactory,
            ITransactionService transactionService,
            IAssetsService assetService,
            IInsActivityService inspectionActivityService,
            ICommonService commonService,
            IDocumentsService documentService,
            IDocumentTypeService documentTypeService,
            IMainGoalService mainGoalService,
            IOrganizationService orgService,
            IIlsmService ilsmService,
            IFrequencyService frequencyService,
            IEpService epService,
            IGoalMasterService goalMasterService,
            IStandardService standardService,
            IStepsService stepService,
            IFloorAssetService floorAssetService,
            IHttpPostFactory httpService,
            IUserService userService,
            IPdfService pdfService,
            IBuildingsService buildingsService,
            IReportsService reportService
            )
        {
            _buildingsService = buildingsService;
            _commonModelFactory = commonModelFactory;
            _transactionService = transactionService;
            _assetService = assetService;
            _documentService = documentService;
            _commonService = commonService;
            _documentTypeService = documentTypeService;
            _ilsmService = ilsmService;
            _goalMasterService = goalMasterService;
            _epService = epService;
            _frequencyService = frequencyService;
            _mainGoalService = mainGoalService;
            _orgService = orgService;
            _inspectionActivityService = inspectionActivityService;
            _standardService = standardService;
            _stepService = stepService;
            _floorAssetService = floorAssetService;
            _userService = userService;
            _httpService = httpService;
            _pdfService = pdfService;
            _reportService = reportService;
        }

        #region Standards

        [CrxAuthorize(Roles = "Goal_Index")]
        public ActionResult Index(string categoryId)
        {
            UISession.AddCurrentPage("Goal_Index", 0, "Setup Master EP");
            ViewBag.Category = _assetService.GetCategory();
            var items = _standardService.Get();
            if (!string.IsNullOrEmpty(categoryId))
                items = items.Where(x => x.CategoryId == Convert.ToInt32(categoryId)).ToList();
            return View(items.OrderBy(x => x.TJCStandard).ToList());
        }

        [HttpGet]
        public ActionResult CreateGoal()
        {
            UISession.AddCurrentPage("Goal_creategoal", 0, "Add Standard");
            ViewBag.Frequencs = _frequencyService.GetFrequency();
            ViewBag.Category = _assetService.GetCategory();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateGoal(BDO.Standard model)
        {
            if (ModelState.IsValid)
            {
                model.CreatedBy = UserSession.CurrentUser.UserId;
                var stdescId = _standardService.AddStandard(model);
                if (stdescId > 0) { SuccessMessage = ConstMessage.Success; return RedirectToAction("Index"); }
                else
                    ErrorMessage = ConstMessage.Error;
            }
            ViewBag.Frequencs = _frequencyService.GetFrequency();
            ViewBag.Category = _assetService.GetCategory();
            return View(model);
        }


        [HttpGet]
        public ActionResult EditStandard(int gid)
        {
            UISession.AddCurrentPage("Goal_editstandard", 0, "Update Standard");
            var stdescId = gid;
            ViewBag.Category = _assetService.GetCategory();
            var objStandard = _standardService.GetStandards().FirstOrDefault(x => x.StDescID == stdescId);
            return View(objStandard);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditStandard(BDO.Standard data)
        {
            if (ModelState.IsValid)
            {
                var status = _standardService.UpdateStandard(data);
                if (status)
                {
                    SuccessMessage = ConstMessage.Success_Updated;
                    return RedirectToRoute("goals");
                }
                else { ErrorMessage = ConstMessage.Error; }
            }
            return View();
        }


        //[CustomAuthorize(Roles = "Remove_Goals")]
        public ActionResult Deletestandard(int gid)
        {
            var stdescId = gid;
            var standard = _standardService.GetStandard(stdescId);
            standard.IsActive = false;
            var status = _standardService.UpdateStandard(standard);
            if (status)
                return RedirectToRoute("goals");
            return RedirectToAction("Index");
        }

        #endregion

        #region EP details

        public ActionResult NonTrackedEPs()
        {
            UISession.AddCurrentPage("goal_NonTrackedEPs", 0, "Non-Tracked EP Report");
            var eps = _epService.GetStandardEPs().Where(x => !x.IsApplicable).ToList();
            return View(eps);
        }

        [HttpGet]
        public ActionResult AddEP(int? stdescId, int? epdetailId)
        {
            UISession.AddCurrentPage("goal_addep", 0, "Add EPs");
            var objEPdetails = new EPDetails();
            ViewBag.RecFrequencyId = "";
            ViewBag.DocTypeId = "";
            ViewBag.TjcFrequencyId = "";
            if (epdetailId.HasValue && epdetailId > 0)
            {
                objEPdetails = _epService.GetEpDetails().FirstOrDefault(x => x.EPDetailId == epdetailId.Value);
                if (objEPdetails != null)
                {
                    if (objEPdetails.EPFrequency != null && objEPdetails.EPFrequency.Count > 0)
                    {
                        ViewBag.RecFrequencyId = objEPdetails.EPFrequency.FirstOrDefault()?.RecFrequencyId;
                        ViewBag.TjcFrequencyId = objEPdetails.EPFrequency.FirstOrDefault()?.TjcFrequencyId;
                    }
                    if (objEPdetails.DocumentType != null && objEPdetails.DocumentType.Count > 0)
                        ViewBag.DocTypeId = objEPdetails.DocumentType.FirstOrDefault()?.DocTypeId;
                }
            }
            else
            {
                objEPdetails.EPDescriptions = _epService.GetHospitalTypeEpDescriptions();
                var frq = new EPFrequency();
                frq.TjcFrequencyId = 0;
                frq.RecFrequencyId = 0;
                objEPdetails.EPFrequency.Add(frq);

            }

            var epPriorityLists = from BDO.Enums.EPPriority d in Enum.GetValues(typeof(BDO.Enums.EPPriority))
                                  select new { ID = (int)d, Name = d.ToString() };
            var epPriority = new SelectList(epPriorityLists, "ID", "Name", objEPdetails?.Priority ?? 0);

            ViewBag.EPPriority = epPriority;
            ViewBag.Frequencs = _frequencyService.GetFrequency().Where(x => x.IsActive).ToList();
            ViewBag.Goals = _standardService.Get().Where(x => x.IsActive).ToList();
            ViewBag.Scores = _orgService.GetScores();
            ViewBag.DocumentTypes = _documentTypeService.GetDocumentTypes();
            ViewBag.StdescId = stdescId ?? 0;
            return View(objEPdetails);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddEP(EPDetails model, string docTypeId, string assetId)
        {
            model.CreatedBy = UserSession.CurrentUser.UserId;
            if (!string.IsNullOrEmpty(docTypeId))
                model.IsDocRequired = true;

            if (!string.IsNullOrEmpty(assetId))
                model.IsAssetsRequired = true;

            var epId = _epService.Save(model);
            model.EPDetailId = epId;
            if (epId > 0)
            {
                if (!string.IsNullOrEmpty(docTypeId))
                    SaveEPDocumentType(epId, docTypeId);

                if (!string.IsNullOrEmpty(assetId))

HCF.Web/Views/Shared/Components/RepositoryGetDocumentEP/Default.cshtml
@model IEnumerable<HCF.BDO.DocumentType>
<input type="hidden" id="duedays" value="@ViewBag.DueDays" />
<table id="documentep" class="table table-bordered table-striped no-footer" width="100%">
    <thead>
        <tr>
            <th style="display:none"></th>
            <th style="display:none"></th>
            <th>Policy Name</th>
            <th>Standard,EP</th>
            <th>Last Review</th>
            <th>Next Review</th>
            <th>Responsible </th>
            <th>View Policy </th>
            <th>View Sample </th>
            <th>History </th>
            <th>Update </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Where(x => x.DocCategoryID == HCF.BDO.Enums.DocCategory.Policy).Where(x => x.EPDocument.Any()))
        {
            var tinspectionEPdocs = new HCF.BDO.InspectionEPDocs();
            var epDocLists = item.TInspectionActivity.OrderByDescending(x => x.ActivityInspectionDate).FirstOrDefault();
            if (epDocLists != null)
            {
                tinspectionEPdocs = epDocLists.InspectionEPDocs;
            }
            <tr id="@item.DocTypeId"
                ondragover="onEPdragOver(event);"
                ondrop="policyEPdrop(event);"
                epid="@string.Join(",", item.EPDocument.Where(x => x.EPDetailId > 0).Select(x => x.EPDetailId))">
                <td style="display:none">
                    @item.DocTypeId
                </td>
                <td style="display:none">
                    @commonModelFactory.GetTranStatus(item.Status)
                </td>
                <td>
                    @*<span>
            <img src="@commonModelFactory.ReturnImagePath(Convert.ToInt32(item.DocStatus),true)"
                 title="@commonModelFactory.ReturnImageTooltip(Convert.ToInt32(item.DocStatus),true)"
                 alt="" />
        </span>*@
                    <span id="statuslabel" class="processType-Sprite @commonModelFactory.GetTranStatus(item.DocStatus)"></span>
                    <span>@item.Name </span>
                </td>
                <td>
                    <ul>
                        @foreach (var epDocs in item.EPDocument.Where(x => x.EPDetailId > 0))
                        {
                            <li>
                                <a href="@Url.Action("EpInspections", "Goal", new { epId = epDocs.EPDetailId })">
                                    @epDocs.StandardEPs.StandardEP
                                </a>
                            </li>
                        }
                    </ul>
                </td>
                <td data-sort="@item.LastUploadedDate.DateSort()">
                    @if (item.LastUploadedDate.HasValue)
                    {
                        <span>
                            @item.LastUploadedDate.CastLocaleDate()
                        </span>
                    }

                </td>
                <td data-sort="@item.NextDueDateDate.DateSort()">
                    @if (item.NextDueDateDate.HasValue)
                    {
                        <span>
                            @item.NextDueDateDate.CastDate()
                        </span>
                    }
                </td>
                <td>
                    <a href="@Url.Action("EpUserView", "Common", new { epDetailId = 0, standardEP = item.Name,docTypeId = item.DocTypeId })"
                       class="modal-link">
                        @{
                            if (item.DocUserProfiles.Any())
                            {
                                var users = item.DocUserProfiles.Where(x => x.IsCRxUser == false).GroupBy(x => x.UserId).Select(x => x.FirstOrDefault()).ToList();

                                var showCounts = 3;
                                var totalCount = users.Count;
                                var usersText = string.Join(",", users.Take(showCounts).Select(x => x.FullName));
                                if (totalCount > showCounts)
                                {
                                    <span>@($"{usersText} +  {totalCount - showCounts}")</span>
                                }
                                else
                                {
                                    <span>
                                        @usersText
                                    </span>
                                }
                            }
                        }
                    </a>

                </td>
                <td>
                    @if (item.NextDueDateDate.HasValue)
                    {
                        <a style="float: left;padding: 3px;" href="@commonModelFactory.FilePath(epDocLists.InspectionEPDocs.Path)" target="_blank">
                            <img src="@Url.Content("~/dist/Images/Icons/policy_doc_icon.png")" alt="">
                        </a>
                    }
                </td>
                <td align="center">
                    <a style="float: left;padding: 3px;" href="@commonModelFactory.CommonFilePath(item.Path)" target="_blank">
                        <img src="@Url.Content("~/dist/Images/Icons/sample_doc_icon.png")" alt="">
                    </a>
                </td>
                <td>
                    @if (item.DocTypeId > 0)
                    {
                        <img class="hover_sign" onclick="location.href ='@Url.Action("PolicyBinderHistory", "Repository", new { docTypeId = item.DocTypeId })'"
                             src="@Url.Content(HCF.Web.Models.ImagePathModel.HistoryIcon)" />
                    }
                    else
                    {
                        <img class="hover_sign" onclick="location.href ='@Url.Action("EpHistory", "Assets", new { epId = item.EPDocument.Where(x => x.EPDetailId > 0).Select(x => x.EPDetailId).FirstOrDefault() })'"
                             src="@Url.Content(HCF.Web.Models.ImagePathModel.HistoryIcon)" />
                    }
                </td>
                <td width="100px">
                    @if (ViewBag.PolicyView == "view")
                    {
                        <a href="@Url.Action("PolicyBinders", "Repository",new { epId= item.EPDocument.Where(x => x.EPDetailId > 0).Select(x => x.EPDetailId).FirstOrDefault()})" class="button3">
                            Update
                        </a>
                    }
                    else
                    {
                        <input docTypeId='@item.DocTypeId'
                               epid="@string.Join(",", item.EPDocument.Where(x => x.EPDetailId > 0).Select(x => x.EPDetailId))"
                               type="button" value='Select' class="btnAddPolicy button1" name="submitType" />
                        <input type="button" value='Remove' class="btnRemovePolicy hide button1" />

                    }
                </td>
            </tr>
        }
    </tbody>
</table>
<script>

    var policyTable = $('#documentep').DataTable({
        "searching": true,
        "lengthChange": false,
        "bPaginate": $('#documentep tbody tr').length > 10,
        "bInfo": false,
        "aaSorting": [],
        "language": {
            "emptyTable": "No data available in table"
        },
        drawCallback: function () {
            $('[rel="popover"]').popover();
        },
        "aoColumnDefs": [{
            'bSortable': false,
            'aTargets': [-1, -2, -3] /* 1st one, start by the right */
        }],
        dom: "<'row'<'col-sm-12'tr>>" +
            "<'row'<'col-sm-5'i><'col-sm-7 text-right'p>>"

    });

    $(document).ready(function () {
        debugger;
        var epCount = '@Model.ToList().Count()';
        if (epCount == 1) {
            try {
                $(".btnAddPolicy").click();
                $(".btnRemovePolicy").addClass("disabled");
                $("#collapseTwo").collapse("true");
            } catch{
            }
        }
    });

</script>
<style>
    .popover {
        min-width: 556px;
    }

    .popover-header .popover-content {
        max-height: 200px;
        overflow: auto;
    }
</style>