HCF.Web/Controllers/PdfController.cs
using HCF.BAL;
using HCF.BAL.Interfaces;
using HCF.BAL.Interfaces.Services;
using HCF.BAL.Ioc;
using HCF.BDO;
using HCF.Utility;
using HCF.Web.Base;
using HCF.Web.Helpers;
using HCF.Web.Localize;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using HCF.Utility.Extensions;
using HCF.BDO.Enums;

namespace HCF.Web.Controllers
{
    [Authorize]
    public class PdfController : BaseController
    {
        private readonly IAssetsService _assetService;
        private readonly IEpService _epService;
        private readonly IFireWatchService _fireWatchService;
        private readonly ICommonService _commonService;
        private readonly IIlsmService _ilsmService;
        private readonly IExercisesService _exercisesService;
        private readonly IUserService _userService;
        private readonly ITransactionService _transactionService;
        private readonly IHotWorkPermitService _hotWorkPermitService;
        private readonly IPCRAService _pcraService;
        private readonly IConstructionService _constructionService;
        private readonly IPermitService _permitService;
        private readonly IInsActivityService _insActivityService;
        private readonly IRoundsService _roundsService;
        private readonly IHttpPostFactory _httpService;
        private readonly IPdfService _pdfService;
        private readonly ICommonModelFactory _commonModelFactory;
        private readonly ISiteService _siteService;
        private readonly IHCFSession _session;
        private readonly IEmailProcessor _emailProcessor;
        private readonly ICommonProvider _commonProvider;
        private readonly IFireExtinguisherService _fireExtinguisherService;

        public PdfController(IWebHostEnvironment hostingEnvironment, ICommonModelFactory commonModelFactory,
            IInsActivityService insActivityService,
            IPCRAService pcraService, IUserService userService,
            IExercisesService exercisesService, IIlsmService ilsmService, IAssetsService assetService, IEpService epService, IFireWatchService fireWatchService,
            ICommonService commonService, ITransactionService transactionService, IHotWorkPermitService hotWorkPermitService, IConstructionService
            constructionService, ICommonProvider commonProvider,
            IHttpPostFactory httpService,
            IPermitService permitService, IEmailProcessor emailProcessor, IRoundsService roundsService, IPdfService pdfService, ISiteService siteService, IHCFSession session, IEmailService emailService,
            IFireExtinguisherService fireExtinguisherService)

        {
            _httpService = httpService;
            _commonModelFactory = commonModelFactory;
            _insActivityService = insActivityService;
            _pcraService = pcraService;
            _userService = userService;
            _exercisesService = exercisesService;
            _ilsmService = ilsmService;
            _commonService = commonService;
            _assetService = assetService;
            _epService = epService;
            _fireWatchService = fireWatchService;
            _transactionService = transactionService;
            _hotWorkPermitService = hotWorkPermitService;
            _constructionService = constructionService;
            _permitService = permitService;
            _roundsService = roundsService;
            _pdfService = pdfService;
            _siteService = siteService;
            _session = session;
            _emailProcessor = emailProcessor;
            _commonProvider = commonProvider;
            _fireExtinguisherService = fireExtinguisherService;
        }


        #region Color       

        public static readonly System.Drawing.Color GrayColor = System.Drawing.Color.FromArgb(231, 231, 231);
        public static readonly BaseColor Gray = new BaseColor(GrayColor);

        public static readonly System.Drawing.Color CyanColor = System.Drawing.Color.FromArgb(0, 162, 232);
        public static readonly BaseColor CYAN = new BaseColor(CyanColor);

        #endregion

        #region Font

        private static readonly Font CellFont = new Font(Font.FontFamily.HELVETICA, 8.5f, Font.NORMAL);
        static readonly Font CellBoldFont = new Font(Font.FontFamily.HELVETICA, 8.5f, Font.BOLD);
        static readonly Font smallfont = new Font(Font.FontFamily.HELVETICA, 8f, Font.NORMAL);
        static readonly Font smallfontbold = new Font(Font.FontFamily.HELVETICA, 8f, Font.BOLD);
        static readonly Font CellFontS = new Font(Font.FontFamily.HELVETICA, 8.5f, Font.NORMAL);
        static readonly Font UnderlineTitleBoldFont = new Font(Font.FontFamily.HELVETICA, 11.5f, Font.BOLD | Font.UNDERLINE);
        static readonly Font UnderlineCellBoldFont = new Font(Font.FontFamily.HELVETICA, 10.5f, Font.BOLD | Font.UNDERLINE);
        static readonly Font UnderlineCellFont = new Font(Font.FontFamily.HELVETICA, 10.5f, Font.UNDERLINE);
        static readonly Font CellFontSmall = new Font(Font.FontFamily.HELVETICA, 8.5f, Font.NORMAL);
        static readonly Font CellFontDatetimeblue = new Font(Font.FontFamily.HELVETICA, 8.5f, Font.NORMAL, CYAN);
        static readonly Font CellFontBold = new Font(Font.FontFamily.HELVETICA, 11f, Font.BOLD);
        static readonly Font TitleFont = new Font(Font.FontFamily.HELVETICA, 16, Font.NORMAL);
        static readonly Font TitleFontS = new Font(Font.FontFamily.HELVETICA, 12, Font.NORMAL);
        static readonly Font UnderlineTitleFont = new Font(Font.FontFamily.HELVETICA, 14, Font.UNDERLINE);
        static readonly Font ParagraphFont = new Font(Font.FontFamily.HELVETICA, 11, Font.NORMAL);
        static readonly Font ParagraphFontS = new Font(Font.FontFamily.HELVETICA, 8.5f, Font.NORMAL);
        static readonly Font Strikethru = new Font(Font.FontFamily.HELVETICA, 11, Font.STRIKETHRU);
        static readonly Font CellFontBoldSmall = new Font(Font.FontFamily.HELVETICA, 8f, Font.BOLD);
        static readonly Font CellFontSmall1 = new Font(Font.FontFamily.HELVETICA, 7.5f, Font.NORMAL);
        static readonly Font CellFontSmall2 = new Font(Font.FontFamily.HELVETICA, 6.5f, Font.NORMAL);
        static readonly Font CellFontBoldSmall2 = new Font(Font.FontFamily.HELVETICA, 6.5f, Font.BOLD, BaseColor.BLACK);
        static readonly Font CellFontBoldBlue = new Font(Font.FontFamily.HELVETICA, 12f, Font.BOLD, BaseColor.BLACK);
        static readonly Font CellFontBoldBlack = new Font(Font.FontFamily.HELVETICA, 8.5f, Font.BOLD);
        static readonly Font CellFontBoldBlueSmall = new Font(Font.FontFamily.HELVETICA, 8.5f, Font.BOLD, BaseColor.BLACK);
        static readonly Font CellFontNormalBlueSmall = new Font(Font.FontFamily.HELVETICA, 8.5f, Font.NORMAL, BaseColor.BLACK);
        static readonly Font CellStatusFont = new Font(Font.FontFamily.HELVETICA, 14f, Font.BOLD, BaseColor.RED);
        static readonly Font CellRedtext = new Font(Font.FontFamily.HELVETICA, 8.5f, Font.BOLD, BaseColor.RED);
        static readonly Font CellFontWhiteBold = new Font(Font.FontFamily.HELVETICA, 10.5f, Font.BOLD, BaseColor.WHITE);
        static readonly Font TitleFontHWP = new Font(Font.FontFamily.HELVETICA, 76f, Font.NORMAL, BaseColor.WHITE);
        static readonly Font TitleFont2HWP = new Font(Font.FontFamily.HELVETICA, 35f, Font.BOLD, BaseColor.BLACK);
        #endregion

        #region  Common Methods

        private void SetHeader(out PdfPTable table)
        {
            table = new PdfPTable(2)
            {
                WidthPercentage = 100,
                //0=Left, 1=Centre, 2=Right
                HorizontalAlignment = 0,
                SpacingBefore = 10f,
                //SpacingAfter = 10f
            };

            //Cell no 1
            PdfPCell cell = new PdfPCell
            {
                Border = 0
            };
            System.Net.ServicePointManager.Expect100Continue = true;
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            Image image = Image.GetInstance(_commonProvider.GetS3StaticImage(UserSession.CurrentOrg.LogoPath));
            image.ScaleAbsolute(100, 80);
            cell.AddElement(image);
            table.AddCell(cell);

            Chunk chunk = new Chunk("" + UserSession.CurrentOrg.Name, FontFactory.GetFont("Arial", 11, Font.NORMAL, BaseColor.BLACK));
            Chunk chunk1 = new Chunk("" + UserSession.CurrentOrg.Address + "", FontFactory.GetFont("Arial", 9, Font.NORMAL, BaseColor.BLACK));
            cell = new PdfPCell
            {
                Border = 0
            };
            cell.AddElement(chunk);
            cell.AddElement(chunk1);

            table.AddCell(cell);


        }
        private void SetHeaderBlue(out PdfPTable table, string Heading)
        {
            table = new PdfPTable(3)
            {
                WidthPercentage = 100,
                //0=Left, 1=Centre, 2=Right
                HorizontalAlignment = 0,
                SpacingBefore = 10f,
                //SpacingAfter = 10f
            };

            float[] widths = new float[] { 15f, 5f, 80f };
            table.SetTotalWidth(widths);

            //Cell no 1
            PdfPCell cell = new PdfPCell
            {
                Border = 0
            };
            System.Net.ServicePointManager.Expect100Continue = true;
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            Image image = Image.GetInstance(_commonProvider.GetS3StaticImage(UserSession.CurrentOrg.LogoPath));
            image.ScaleAbsolute(80, 80);
            image.SetAbsolutePosition(10, 0);
            cell.AddElement(image);
            table.AddCell(cell);

            PdfPCell cell2 = new PdfPCell

HCF.Web/Views/FireWatch/FireWatch.cshtml
@{
    ViewBag.Title = "Fire Watch";
}

@section pageHeader{

    <section class="content-header">
        <h1>
            Fire Watch Log
        </h1>
    </section>
}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">


                <div class="row tablelist-topform">
                    <div class="col-md-8 form-inline">
                        <div class="form-group">
                            <label>Date:</label>
                            <input type="text" name="date" class="datepicker form-control" id="watcherdate" style="min-width: 240px;" readonly="readonly" />
                            <input type="hidden" id="mode" value="@ViewBag.Mode" />
                        </div>
                        <div class="form-group">
                            <label>Building Name:</label>
                            @*@Html.BuildingDropDownList("BuildingId", 0, "Select Building", new { @class = "form-control", required = "required" })*@

                            <buildingdropdownlist firsttext="All Building"
                                                  required="required"
                                                  class="form-control"
                                                  selectedvalue="0"
                                                  name="BuildingId">
                            </buildingdropdownlist>
                        </div>
                    </div>
                    <div class="col-md-4 form-group text-right">
                        <strong>History: </strong> <img onclick="location.href ='@Url.Action("FireWatchHistory", "FireWatch")'"
                                                        src="@Url.Content(HCF.Web.Models.ImagePathModel.HistoryIcon)" title="History" />
                    </div>
                </div>



                <div class="row" id="loadpartial">

                </div>

            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>

    var minDate = -1;
        var hasFirewatch = '@commonModelFactory.IsFireWatchSupervisorUser()';
        //var hasFirewatch = userTypeIds.indexOf('7') != -1;
        if (hasFirewatch.toLowerCase() == "true") {
            minDate = -730;
        }


    $('.datepicker').datepicker({
        showOn: "both",
        buttonImage: "@Url.Content(HCF.Web.Models.ImagePathModel.CalendarDatePicketIcon)",
        buttonImageOnly: true,
        minDate: minDate,
        maxDate: new Date(),
        beforeShow: changeYearButtons,
        onChangeMonthYear: changeYearButtons,
        dateFormat: $.CRx_DateFormat
    }).datepicker('setDate', 'today');


    $(document).ready(function () {
        var mode = $('#mode').val();
        debugger;
        if (mode == "Edit") {
            $('.alert').hide();
            $('.alert-success').hide();
        }
        loaddata();
    });

        $('#watcherdate').change(function () {
            loaddata();
        });

        $(document).on("change", "#BuildingId", function () {
            loaddata();
        });




    function loaddata() {
       //debugger
        var date = $("#watcherdate").val();
        var buildingID = $("#BuildingId").val();
        var url = '@Url.Action("LogFireWatch", "FireWatch")'
        $.ajax({
            url: url + '?selecteddate=' + date + '&buildingID=' + buildingID,
            cache: false,
            type: "GET",
            success: function (data) {
                $('#loadpartial').html(data);
                $('#loadpartial').fadeIn('fast');
            }
        });
    }



    </script>
}

HCF.Web/Views/FireWatch/FireWatchHistory.cshtml
@{
    ViewBag.Title = " Fire Watch Log History";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


    @section pageHeader{
    <section class="content-header">
        <h1>
            Fire Watch History
        </h1>
    </section>
        }
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                   
                       
                            
                    <div class="row tablelist-topform">
                        <div class="" id="dvreportCntrl" style="display: none; border-bottom: 1px solid #ddd; padding-bottom: 10px; margin-bottom: 10px; overflow: auto;">
                            <div class="col-md-8 form-inline">
                                <div class="form-group">
                                    <label>From</label>
                                    <input type="text" id="fromdate" class="form-control datepicker" readonly="readonly" />
                                </div>
                                <div class="form-group">
                                    <label>To</label>
                                    <input type="text" id="todate" class="form-control datepicker" readonly="readonly" />
                                </div>
                            </div>
                            <div class="col-lg-4 text-right">
                                @using (Html.BeginForm("FireWatchReports", "Pdf", FormMethod.Post, new { id = "fireWatchReports" }))
                                {
                                    @Html.AntiForgeryToken()
                                    <input type="hidden" name="sFromdate" id="sFromdate" />
                                    <input type="hidden" name="sTodate" id="sTodate" />
                                    <button type="button" class="comm-button" id="Generate-firewatch-report">Generate FireWatch Report</button>
                                }
                                @*<input type="submit" name="button" class="comm-button" value="Generate Report" />*@
                            </div>
                        </div>
                        <div class="col-md-12 text-right">
                            <button class="comm-button" id="btnreport">Show Report Filter</button>
                            @*<input type="submit" name="button" class="comm-button" value="Show Report Filter" id="btnreport" />*@
                            <input type="submit" name="button" class="comm-button" value="My FireWatch Schedule " onclick="location.href = '@Url.Action("FireWatch", "FireWatch")'" />
                        </div>
                    </div>
                       
                    <div class="row">
                        <div class="col-md-6">
                            <div id='calendar' class="calender"></div>
                        </div>
                        <div class="col-md-6">
                            <div id="historyTab">
                                @await Component.InvokeAsync("FireWatchFireWatchHistoryDetails") 
                            </div>
                        </div>
                    </div>
                   
                </div>
            </div>
        </div>
    </div>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.0.1/fullcalendar.min.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.16.0/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.0.1/fullcalendar.min.js"></script>

<script type="text/javascript">

    $('#calendar').fullCalendar({
        header: {
            left: '',
            center: 'prevYear,prev,title,next,nextYear',
            right: 'today'
        },
        selectable: true,
        selectConstraint: {
            start: $.fullCalendar.moment().subtract(1, 'days'),
            end: $.fullCalendar.moment().startOf('month').add(1, 'month')
        },
       
        firstDay: 0,
        slotMinutes: 0,
        events: '@Url.RouteUrl(new { action = "GetEvents", controller = "FireWatch" })',
        dayClick: function (date, jsEvent, view) {
            openHistoryPage(date);
            $("td").removeClass("activeDate");
            $(this).addClass("activeDate");
        },
        eventClick: function (calEvent, jsEvent, view) {
            var dt = calEvent.start;

            $("td").removeClass("activeDate");
            //openHistoryPage(dt);
            $('.fc-day[data-date="' + getEventDate(dt) + '"]').addClass("activeDate");
        }
    });

    $("td.fc-today").addClass("activeDate");


    function getEventDate(timestamp) {
        var dateobj = new Date(timestamp);
        var month = Number(dateobj.getMonth() + 1);
        var newmonth = month < 10 ? '0' + month : '' + month;
        date = dateobj.getFullYear() + '-' + newmonth + '-' + dateobj.getDate();
        return date;
    }

    function openHistoryPage(timeSpan) {
        var url = '@Url.Action("FireWatchHistoryDetails", "FireWatch")';
        $.ajax({
            url: url + "?timeSpan=" + timeSpan,
            cache: false,
            type: "GET",
            success: function (data) {
                $('.fc-day[data-date="' + getEventDate(timeSpan) + '"]').addClass("activeDate");
                console.log($('.fc-day[data-date="' + getEventDate(timeSpan) + '"]').addClass("activeDate"));
                $('#historyTab').empty();
                $('#historyTab').html(data);
                $('#historyTab').fadeIn('fast');
            }
        });
    }

    $(".fc-today-button").click(function () {
        $("td.fc-today").addClass("activeDate");
        openHistoryPage("");
    });

        $(function () {
        var currentTime = new Date();
        debugger;
            var startDate = new Date(currentTime.setMonth(currentTime.getMonth() - 1)); //new Date(currentTime.getFullYear(), currentTime.getMonth() - 1, 1);
        var dateFormat = "mm/dd/yy",
            from = $("#fromdate")
                .datepicker({
                    //defaultDate: "+1w",
                    changeMonth: true,
                    changeYear: true,
                    maxDate: new Date(),
                    minDate:new Date(2018,0,1),
                    numberOfMonths: 1,
                    buttonImage: "@Url.Content(HCF.Web.Models.ImagePathModel.CalendarDatePicketIcon)",
                    buttonImageOnly: true
                }).datepicker('setDate', startDate)
                .on("change", function () {
                    to.datepicker("option", "minDate", getDate(this));
                }),
            to = $("#todate").datepicker({
                //defaultDate: "+1w",
                changeMonth: true,
                changeYear: true,
                maxDate: new Date(),
                minDate: new Date(2018, 0, 1),
                numberOfMonths: 1,
                buttonImage: "@Url.Content(HCF.Web.Models.ImagePathModel.CalendarDatePicketIcon)",
                buttonImageOnly: true
            }).datepicker('setDate', 'today')
                .on("change", function () {
                    from.datepicker("option", "maxDate", getDate(this));
                });

        function getDate(element) {
            var date;
            try {
                date = $.datepicker.parseDate(dateFormat, element.value);
            } catch (error) {
                date = null;
            }

            return date;
        }
        //loadData();
    });


    $("#btnreport").click(function () {
        debugger;
        $(this).text($(this).text() == 'Show Report Filter' ? 'Hide Report Filter' : 'Show Report Filter');
        $("#dvreportCntrl").toggle();
    });


    $("#Generate-firewatch-report").click(function () {
        var form = document.getElementById("fireWatchReports");
        debugger;
        var _fromdate = $("#fromdate").val();
        var _todate = $("#todate").val();
        $("#sFromdate").val(_fromdate);
        $("#sTodate").val(_todate);
        form.submit();
    })

</script>
<style>
    .calender {
        border: #ddd solid 1px;
        width: 100%;
    }

    .fc-toolbar {
        margin-bottom: 0 !important;
    }

    .fc-toolbar {
        margin-bottom: 0;
        padding: 5px;
        background: #f5f5f5;
    }

    .fc-scroller.fc-day-grid-container {
        height: auto !important;
    }

    .fc .fc-toolbar > * > :first-child {
        display: flex;
    }

    .fc-widget-header:last-of-type, .fc-widget-content:last-of-type {
        border: 1px solid #ddd;
    }

    .fc .fc-toolbar > * > :first-child {
        line-height: 20px;
    }

   

    .fc-toolbar .fc-center {
        font-size: 10px;
    }

    .fc-toolbar h2 {
        font-size: 20px;
        display: inline-block;
        margin: 0 12px;
        vertical-align: middle;
    }

    .fc-today-button {
        height: 23px !important;
        font-size: 12px !important;
    }

    .fc td, .fc th {
        font-size: 15px;
    }

    .fc-basic-view .fc-day-number, .fc-basic-view .fc-week-number {
        padding: 8px !important;
        font-weight: 500;
    }

    .fc-day-number {
        font-size: 15px;
    }

    .fc th {
        padding: 5px 0 !important;
        font-size: 14px;
    }

    .fc-today {
        border: none !important;
        border-top: 1px solid #ddd !important;
        font-weight: bold;
    }

    tr:first-child > td > .fc-day-grid-event {
        margin-top: -4px;
    }

    .fc-toolbar {
        margin-bottom: 0;
        padding: 5px;
        background: #f5f5f5;
    }

    .fc-widget-content {
        padding: 0px !important;
    }

    .fc-time {
        display: none;
    }

    .fc-event {
        width: 24px !important;
        text-align: center !important;
    }



    .fc-day-header span {
        color: #171717;
    }

    .fc-scroller {
        overflow-x: visible !Important;
    }
</style>